### ISSUE TITLE
Support for thud and warrior + branch naming

### ISSUE THREAD

**Issue by vicgal** [compulab-yokneam/meta-bsp-imx8mq#1]
Hello,

When trying to update the yocto layers to thud or warrior,  to build the compulab image for the cl-som-imx8 machine, the build stops with:
`ERROR: Layer compulab-bsp is not compatible with the core layer which only supports these series: thud (layer is compatible with sumo)`
This seems to be coming from the `meta-bsp-imx8mq/conf/layer.conf` :
`LAYERSERIES_COMPAT_compulab-bsp = "sumo"`
Could you please estimate when are you planning to update the `meta-bsp-imx8mq` to `thud` or `warrior`?
And when doing that could you please create separate branches for `sumo`, `thud` and `warrior` (and if applicable other yocto release this layer supports)?

Regards

**Comment by vraevsky** [comment]
Added a zeus deveolpment branch.
