### ISSUE TITLE
Build failes if you do not select chromium during setup

### ISSUE THREAD

**Issue by parrotruper** [compulab-yokneam/meta-bsp-imx8mq#3]
During setup of environment you are prompted whether you want chromium if you select the No option the build fails when compiling QT.

**Comment by vraevsky** [comment]
Please use this branch:
https://github.com/compulab-yokneam/meta-bsp-imx8mq/tree/devel-next

**Comment by vraevsky** [comment]
Probably the missing "git-lfs" was the reason while at fails.
Fixed by this commit: https://github.com/compulab-yokneam/meta-bsp-imx8mq/commit/e7577a49c988fde20ba91793ac67d407420c20cc
